import "./globals.css";
import type { Metadata } from "next";

import { cedarvilleFont, syneFont } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${cedarvilleFont.variable} ${syneFont.variable}`}>
      <body className="overflow-hidden min-h-screen">{children}</body>
    </html>
  );
}
